In [58]:
import numpy as np
import pandas as pd

In [59]:
data=pd.read_csv('Loan Dataset.csv')
data.head()

,Applicant_ID,Gender,Age,Marital_Status,Dependents,Education,Employment_Status,Occupation_Type,Residential_Status,City/Town,Annual_Income,Monthly_Expenses,Credit_Score,Existing_Loans,Total_Existing_Loan_Amount,Outstanding_Debt,Loan_History,Loan_Amount_Requested,Loan_Term,Loan_Purpose,Interest_Rate,Loan_Type,Co-Applicant,Bank_Account_History,Transaction_Frequency,Default_Risk,Loan_Approval_Status
0,1,Female,25,Married,2,Graduate,Employed,Business,Own,Urban,139901,2533,743,0,10942,19822,0,24535,209,Home,4.27,Secured,Yes,8,20,0.81,1
1,2,Male,36,Married,2,High School,Employed,Business,Own,Suburban,21162,4041,468,1,48731,18321,0,8288,33,Home,14.78,Unsecured,Yes,9,9,0.17,0
2,3,Male,43,Single,0,Postgraduate,Self-Employed,Freelancer,Own,Urban,27815,3453,389,2,6925,13851,0,10308,159,Vehicle,12.33,Secured,Yes,7,27,0.25,0
3,4,Female,28,Married,0,High School,Self-Employed,Freelancer,Rent,Suburban,137853,2732,778,0,42016,28608,1,33937,39,Personal,8.77,Secured,No,9,16,0.27,1
4,5,Female,32,Single,0,Graduate,Employed,Salaried,Rent,Suburban,81753,1648,752,2,31747,8780,1,23360,34,Home,9.04,Unsecured,No,1,17,0.32,1

In [60]:
import pandas as pd

pd.set_option('display.max_columns', None)

data.head()

,Applicant_ID,Gender,Age,Marital_Status,Dependents,Education,Employment_Status,Occupation_Type,Residential_Status,City/Town,Annual_Income,Monthly_Expenses,Credit_Score,Existing_Loans,Total_Existing_Loan_Amount,Outstanding_Debt,Loan_History,Loan_Amount_Requested,Loan_Term,Loan_Purpose,Interest_Rate,Loan_Type,Co-Applicant,Bank_Account_History,Transaction_Frequency,Default_Risk,Loan_Approval_Status
0,1,Female,25,Married,2,Graduate,Employed,Business,Own,Urban,139901,2533,743,0,10942,19822,0,24535,209,Home,4.27,Secured,Yes,8,20,0.81,1
1,2,Male,36,Married,2,High School,Employed,Business,Own,Suburban,21162,4041,468,1,48731,18321,0,8288,33,Home,14.78,Unsecured,Yes,9,9,0.17,0
2,3,Male,43,Single,0,Postgraduate,Self-Employed,Freelancer,Own,Urban,27815,3453,389,2,6925,13851,0,10308,159,Vehicle,12.33,Secured,Yes,7,27,0.25,0
3,4,Female,28,Married,0,High School,Self-Employed,Freelancer,Rent,Suburban,137853,2732,778,0,42016,28608,1,33937,39,Personal,8.77,Secured,No,9,16,0.27,1
4,5,Female,32,Single,0,Graduate,Employed,Salaried,Rent,Suburban,81753,1648,752,2,31747,8780,1,23360,34,Home,9.04,Unsecured,No,1,17,0.32,1

In [61]:
data.columns

Index(['Applicant_ID', 'Gender', 'Age', 'Marital_Status', 'Dependents',
       'Education', 'Employment_Status', 'Occupation_Type',
       'Residential_Status', 'City/Town', 'Annual_Income', 'Monthly_Expenses',
       'Credit_Score', 'Existing_Loans', 'Total_Existing_Loan_Amount',
       'Outstanding_Debt', 'Loan_History', 'Loan_Amount_Requested',
       'Loan_Term', 'Loan_Purpose', 'Interest_Rate', 'Loan_Type',
       'Co-Applicant', 'Bank_Account_History', 'Transaction_Frequency',
       'Default_Risk', 'Loan_Approval_Status'],
      dtype='object')

In [62]:
data.shape

(52000, 27)

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Applicant_ID                52000 non-null  int64
 1   Gender                      52000 non-null  object
 2   Age                         52000 non-null  int64
 3   Marital_Status              52000 non-null  object
 4   Dependents                  52000 non-null  int64
 5   Education                   52000 non-null  object
 6   Employment_Status           52000 non-null  object
 7   Occupation_Type             52000 non-null  object
 8   Residential_Status          52000 non-null  object
 9   City/Town                   52000 non-null  object
 10  Annual_Income               52000 non-null  int64
 11  Monthly_Expenses            52000 non-null  int64
 12  Credit_Score                52000 non-null  int64
 13  Existing_Loans              52000 non-null  int64
 14  Total_Existing_Loan_Amount  52000 non-null  int64
 15  Outstanding_Debt            52000 non-null  int64
 16  Loan_History                52000 non-null  int64
 17  Loan_Amount_Requested       52000 non-null  int64
 18  Loan_Term                   52000 non-null  int64
 19  Loan_Purpose                52000 non-null  object
 20  Interest_Rate               52000 non-null  float64
 21  Loan_Type                   52000 non-null  object
 22  Co-Applicant                52000 non-null  object
 23  Bank_Account_History        52000 non-null  int64
 24  Transaction_Frequency       52000 non-null  int64
 25  Default_Risk                52000 non-null  float64
 26  Loan_Approval_Status        52000 non-null  int64
dtypes: float64(2), int64(15), object(10)
memory usage: 10.7+ MB

In [64]:
data.isnull().sum()

Applicant_ID                  0
Gender                        0
Age                           0
Marital_Status                0
Dependents                    0
Education                     0
Employment_Status             0
Occupation_Type               0
Residential_Status            0
City/Town                     0
Annual_Income                 0
Monthly_Expenses              0
Credit_Score                  0
Existing_Loans                0
Total_Existing_Loan_Amount    0
Outstanding_Debt              0
Loan_History                  0
Loan_Amount_Requested         0
Loan_Term                     0
Loan_Purpose                  0
Interest_Rate                 0
Loan_Type                     0
Co-Applicant                  0
Bank_Account_History          0
Transaction_Frequency         0
Default_Risk                  0
Loan_Approval_Status          0
dtype: int64

In [65]:
data.duplicated().sum()

np.int64(0)

In [66]:
data['Loan_Approval_Status'].value_counts()

Loan_Approval_Status
1    33366
0    18634
Name: count, dtype: int64

In [67]:
data.drop(['Applicant_ID','Gender','Age','Marital_Status','Residential_Status','City/Town','Bank_Account_History','Transaction_Frequency'], axis=1, inplace=True)
data.head()

,Dependents,Education,Employment_Status,Occupation_Type,Annual_Income,Monthly_Expenses,Credit_Score,Existing_Loans,Total_Existing_Loan_Amount,Outstanding_Debt,Loan_History,Loan_Amount_Requested,Loan_Term,Loan_Purpose,Interest_Rate,Loan_Type,Co-Applicant,Default_Risk,Loan_Approval_Status
0,2,Graduate,Employed,Business,139901,2533,743,0,10942,19822,0,24535,209,Home,4.27,Secured,Yes,0.81,1
1,2,High School,Employed,Business,21162,4041,468,1,48731,18321,0,8288,33,Home,14.78,Unsecured,Yes,0.17,0
2,0,Postgraduate,Self-Employed,Freelancer,27815,3453,389,2,6925,13851,0,10308,159,Vehicle,12.33,Secured,Yes,0.25,0
3,0,High School,Self-Employed,Freelancer,137853,2732,778,0,42016,28608,1,33937,39,Personal,8.77,Secured,No,0.27,1
4,0,Graduate,Employed,Salaried,81753,1648,752,2,31747,8780,1,23360,34,Home,9.04,Unsecured,No,0.32,1

In [68]:
data['Loan_Income_Ratio'] = (
    data['Loan_Amount_Requested'] / data['Annual_Income']
)

In [69]:
data['Loan_Income_Ratio'].head()

0    0.175374
1    0.391645
2    0.370591
3    0.246183
4    0.285739
Name: Loan_Income_Ratio, dtype: float64

In [70]:
data.head()

,Dependents,Education,Employment_Status,Occupation_Type,Annual_Income,Monthly_Expenses,Credit_Score,Existing_Loans,Total_Existing_Loan_Amount,Outstanding_Debt,Loan_History,Loan_Amount_Requested,Loan_Term,Loan_Purpose,Interest_Rate,Loan_Type,Co-Applicant,Default_Risk,Loan_Approval_Status,Loan_Income_Ratio
0,2,Graduate,Employed,Business,139901,2533,743,0,10942,19822,0,24535,209,Home,4.27,Secured,Yes,0.81,1,0.175374
1,2,High School,Employed,Business,21162,4041,468,1,48731,18321,0,8288,33,Home,14.78,Unsecured,Yes,0.17,0,0.391645
2,0,Postgraduate,Self-Employed,Freelancer,27815,3453,389,2,6925,13851,0,10308,159,Vehicle,12.33,Secured,Yes,0.25,0,0.370591
3,0,High School,Self-Employed,Freelancer,137853,2732,778,0,42016,28608,1,33937,39,Personal,8.77,Secured,No,0.27,1,0.246183
4,0,Graduate,Employed,Salaried,81753,1648,752,2,31747,8780,1,23360,34,Home,9.04,Unsecured,No,0.32,1,0.285739

In [71]:
data['Annual_Expenses'] = data['Monthly_Expenses'] * 12

data['Savings'] = (
    data['Annual_Income'] - data['Annual_Expenses']
)

In [72]:
data['Savings'].head()

0    109505
1    -27330
2    -13621
3    105069
4     61977
Name: Savings, dtype: int64

In [73]:
data['Estimated_EMI'] = (
    data['Loan_Amount_Requested'] / data['Loan_Term']
)

In [74]:
data['Estimated_EMI'].head()

0    117.392344
1    251.151515
2     64.830189
3    870.179487
4    687.058824
Name: Estimated_EMI, dtype: float64

In [75]:
data['Credit_Category'] = pd.cut(
    data['Credit_Score'],
    bins=[300,580,670,740,850],
    labels=['Poor','Fair','Good','Excellent']
)

In [76]:
data['Credit_Category'].head()

0    Excellent
1         Poor
2         Poor
3    Excellent
4    Excellent
Name: Credit_Category, dtype: category
Categories (4, object): ['Poor' < 'Fair' < 'Good' < 'Excellent']

In [77]:
data['Expense_Income_Ratio'] = (
    (data['Monthly_Expenses'] * 12)
    / data['Annual_Income']
)

In [78]:
data['Expense_Income_Ratio'].head()

0    0.217268
1    2.291466
2    1.489700
3    0.237819
4    0.241899
Name: Expense_Income_Ratio, dtype: float64

In [79]:
data.to_csv("Cleaned_data.csv")

In [80]:
data['Education'] = (
    data['Education'] == 'Graduate'
).astype(int)

data['Employment_Status'] = (
    data['Employment_Status'] == 'Employed'
).astype(int)

data['Co-Applicant'] = (
    data['Co-Applicant'] == 'Yes'
).astype(int)

In [81]:
X = data[
    [
        'Education',
        'Employment_Status',
        'Co-Applicant',
        'Annual_Income',
        'Monthly_Expenses',
        'Credit_Score',
        'Loan_Amount_Requested',
        'Loan_Term',
        'Savings',
        'Loan_Income_Ratio',
        'Estimated_EMI'
    ]
]

y = data['Loan_Approval_Status']

In [82]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [83]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)

In [84]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
lr_accuracy = accuracy_score(y_test, lr_pred)

C:\Users\Saurav Kumar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [85]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)

In [86]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)

xgb_accuracy = accuracy_score(y_test, xgb_pred)

In [87]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        lr_accuracy,
        dt_accuracy,
        rf_accuracy,
        xgb_accuracy
    ]
})

print(results.sort_values(by="Accuracy", ascending=False))

                 Model  Accuracy
2        Random Forest  0.855769
0  Logistic Regression  0.855481
3              XGBoost  0.853558
1        Decision Tree  0.740865

In [88]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        rf_pred
    )
)

              precision    recall  f1-score   support

           0       0.85      0.71      0.77      3603
           1       0.86      0.93      0.89      6797

    accuracy                           0.86     10400
   macro avg       0.85      0.82      0.83     10400
weighted avg       0.86      0.86      0.85     10400

In [89]:
print(data['Loan_Approval_Status'].value_counts())

Loan_Approval_Status
1    33366
0    18634
Name: count, dtype: int64

In [90]:
import pandas as pd

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

print(
    importance.sort_values(
        by='Importance',
        ascending=False
    )
)

                  Feature  Importance
5            Credit_Score    0.367517
6   Loan_Amount_Requested    0.319140
3           Annual_Income    0.136681
8                 Savings    0.065312
10          Estimated_EMI    0.058362
9       Loan_Income_Ratio    0.029856
4        Monthly_Expenses    0.010741
7               Loan_Term    0.009142
1       Employment_Status    0.001140
0               Education    0.001075
2            Co-Applicant    0.001035

In [91]:
from sklearn.metrics import roc_auc_score

probs = rf.predict_proba(X_test)[:,1]

print(roc_auc_score(y_test, probs))

0.8239785017234466

In [92]:
print(data.groupby('Loan_Approval_Status')['Credit_Score'].mean())

Loan_Approval_Status
0    546.002737
1    751.855602
Name: Credit_Score, dtype: float64

In [93]:
print(data.groupby('Loan_Approval_Status')['Annual_Income'].mean())

Loan_Approval_Status
0    61020.549587
1    96192.044237
Name: Annual_Income, dtype: float64

In [94]:
print(data['Loan_Approval_Status'].corr(data['Credit_Score']))
print(data['Loan_Approval_Status'].corr(data['Annual_Income']))
print(data['Loan_Approval_Status'].corr(data['Savings']))

0.6169770800783196
0.4721445402367602
0.4314292452183752

In [95]:
import pickle

pickle.dump(rf, open('LoanApprovalModel.pkl', 'wb'))

print("Model saved successfully!")

Model saved successfully!